### ISSUE TITLE
MSI Error 1639: 'Invalid command line argument' during installation

### ISSUE THREAD

**Issue by Boscop** [Diggsey/multirust-rs#89] opened 2016-03-09 08:56 UTC
After fresh install on Windows 8.1 (Win32 MSVC Installer), when doing
`$ multirust update nightly`
I get:
```
[...]
checksum passed
extracting...
```
Then a popup from msiexec.exe showing the usage (cmd line flags etc.) with an OK button.
When I click OK, I get:
`error: command failed: 'msiexec' (Status: exit code: 1639)`
Using SysInternals procexp to find the cmd line args:
`msiexec /a "D:\Program Files\.multirust\tmp\u1q7cfw7ur9ke261_file.msi" /qn "TARGETDIR=D:\Program Files\.multirust\tmp\xr8xy3cg51_lssog_dir"`
(Btw, my `MULTIRUST_HOME` is `"D:\Program Files\.multirust"`)

As far as I see it, the issue is the quotes around `"TARGETDIR=<path>"`, shouldn't the quotes be only around the path (like `TARGETDIR="<path>"`)?

**Comment by nodakai** [comment] 2016-03-09 10:53
I had a similar issue; shown below is a transcript (though not as informative as that from `procexp`)
```
C:\Users\nodakai>multirust -v update stable
read metadata version: '2'
info: installing toolchain 'stable'
toolchain directory: 'C:\Users\nodakai\AppData\Local\.multirust\toolchains\stable'
creating temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\fsgx3f4sf6jzk8kw_file
downloading file from: 'https://static.rust-lang.org/dist/channel-rust-stable.sha256'
deleted temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\fsgx3f4sf6jzk8kw_file
creating temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\h96xbpnesksho_cz_file
downloading file from: 'https://static.rust-lang.org/dist/channel-rust-stable'
checksum passed
creating temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\qlelbm_wheilv_ls_file
downloading file from: 'https://static.rust-lang.org/dist/rust-1.7.0-x86_64-pc-windows-gnu.msi.sha256'
deleted temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\qlelbm_wheilv_ls_file
no update hash at: 'C:\Users\nodakai\AppData\Local\.multirust\update-hashes\stable'
creating temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\qqfcjqbtji89jt41_file.msi
downloading file from: 'https://static.rust-lang.org/dist/rust-1.7.0-x86_64-pc-windows-gnu.msi'
92.05 MiB / 92.05 MiB (100.00%) 316.80 KiB/s ETA: 0s
checksum passed
deleted temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\h96xbpnesksho_cz_file
extracting...
creating temp directory: C:\Users\nodakai\AppData\Local\.multirust\tmp\l3wd5pgwhvpbmy18_dir
deleted temp directory: C:\Users\nodakai\AppData\Local\.multirust\tmp\l3wd5pgwhvpbmy18_dir
deleted temp file: C:\Users\nodakai\AppData\Local\.multirust\tmp\qqfcjqbtji89jt41_file.msi
error: command failed: 'msiexec' (Status: exit code: 1603)

C:\Users\nodakai>
```

I'm not an Admin on this machine.

**Comment by Diggsey** [comment] 2016-03-09 11:06
This is a duplicate of #33 

The underlying cause, as mentioned there, is a limitation of rust's `Command` API: rust-lang/rust#29494

**Closed by Diggsey** 2016-03-09 11:06 UTC
